image: gcc:9.3

stages:
  - build-and-secrets
  - test-and-install
  - debug-build
  - debug-test
  - centos-build-and-debug
  - centos-test-and-install


# Build / test / install on CentOS 8, only for main branches

#build_centos_8:
#  image: centos:8
#  tags:
#    - docker
#  stage: centos-build-and-debug
#  before_script:
#    - yum -y update && yum -y groupinstall "Development Tools" && yum -y install make autoconf cmake numactl-devel
#  script:
#    - rm -rf build install && mkdir -p install && ./configure --prefix=./install && cd ./build && make -j$(nproc) && make -j$(nproc) build_tests_all
#  only:
#    - master
#    - develop
#  artifacts:
#    paths:
#      - build/
#    exclude:
#      - build/**/*.o
#      - build/**/*.o.d
#    expire_in: 30 minutes


#build_debug_centos_8:
#  image: centos:8
#  tags:
#    - docker
#  stage: centos-build-and-debug
#  before_script:
#    - yum -y update && yum -y groupinstall "Development Tools" && yum -y install make autoconf cmake numactl-devel
#  script:
#    - mkdir -p install && ./configure --prefix=./install --debug-build && cd ./build && make -j$(nproc) && make -j$(nproc) build_tests_all
#  only:
#    - master
#    - develop


#test_centos_8_unit:
#  image: centos:8
#  tags:
#    - docker
#  stage: centos-test-and-install
#  before_script:
#    - yum -y update && yum -y groupinstall "Development Tools" && yum -y install make autoconf cmake numactl-devel
#  script:
#    - cd ./build && make -j$(nproc) tests_unit &> unittests.log
#    - ../tests/summarise.sh unittests.log
#  only:
#    - master
#    - develop


#test_centos_8_smoke:
#  image: centos:8
#  tags:
#    - docker
#  stage: centos-test-and-install
#  before_script:
#    - yum -y update && yum -y groupinstall "Development Tools" && yum -y install make autoconf cmake numactl-devel
#  script:
#    - cd ./build && make -j$(nproc) tests_smoke &> smoketests.log
#    - ../tests/summarise.sh smoketests.log
#  only:
#    - master
#    - develop


#test_centos_8_performance:
#   image: centos:8
#   tags:
#     - docker
#   stage: centos-test-and-install
#   before_script:
#     - yum -y update && yum -y groupinstall "Development Tools" && yum -y install make autoconf cmake numactl-devel
#   script:
#     - cd ./build &&  make -j$(nproc) tests_performance &> performancetests.log
#     - ../tests/summarise.sh performancetests.log tests/performance/output/benchmarks tests/performance/output/scaling
#   only:
#     - master
#     - develop


#test_centos_8_installation:
#  image: centos:8
#  tags:
#    - docker
#  stage: centos-test-and-install
#  before_script:
#    - yum -y update && yum -y groupinstall "Development Tools" && yum -y install make autoconf cmake numactl-devel
#  script:
#    - cd ./build && make -j$(nproc) install
#  only:
#    - master
#    - develop


# Main testing on Ubuntu, all branches

build_test:
  image: gcc:9.3
  tags:
    - docker
  stage: build-and-secrets
  before_script:
    - apt update && apt -y install make cmake libnuma-dev coreutils
  script:
    - mkdir -p install && ./configure --prefix=./install && cd ./build && make -j$(nproc) build_tests_all
  artifacts:
    paths:
      - build/
    exclude:
      - build/**/*.o
      - build/**/*.o.d
    expire_in: 30 minutes


build_debug2_tests:
  image: gcc:9.3
  tags:
    - docker
  stage: debug-build
  before_script:
    - apt update && apt -y install make cmake libnuma-dev coreutils
  script:
    - mkdir -p install && mkdir -p build && cd build && cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_CXX_FLAGS=-D_DEBUG -DCMAKE_C_FLAGS=-D_DEBUG -DCMAKE_BUILD_TYPE=Debug ../ && make -j$(nproc) build_tests_all


build_debugrelease_tests:
  image: gcc:9.3
  tags:
    - docker
  stage: build-and-secrets
  before_script:
    - apt update && apt -y install make cmake libnuma-dev coreutils
  script:
    - mkdir -p install && mkdir -p build && cd build && cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_CXX_FLAGS=-D_DEBUG -DCMAKE_C_FLAGS=-D_DEBUG -DCMAKE_BUILD_TYPE=Release ../ && make -j$(nproc) build_tests_all
  only:
    - master
    - develop


# linting is currently disabled since clang-format is not mature enough
# and leads to weirdnesses and instabilities; we may reactivate it in future
#
# clang_linter:
#   image: ubuntu:20.04
#   tags:
#     - docker
#   stage: build-and-secrets
#   before_script:
#     - export DEBIAN_FRONTEND=noninteractive
#     - apt update && apt install -y clang-format-11 git-core coreutils
#   script:
#     - tools/clang-format-linter.sh -i --lint-whole-grb
#     - files="$(git status -s)"
#     - if [[ ! -z "${files}" ]]; then echo "The following files do not abide by the official code style, you may use tools/clang-format-linter.sh to format them"; echo "${files[@]}"; else echo 'All files formatted correctly'; fi
#     - if [[ ! -z "${files}" ]]; then exit 0; fi


tests_unit:
  tags:
    - docker
  stage: test-and-install
  before_script:
    - apt update && apt -y install make cmake libnuma-dev coreutils
  script:
    - cd ./build && make -j$(nproc) tests_unit &> unittests.log
    - ../tests/summarise.sh unittests.log


tests_smoke:
  tags:
    - docker
  stage: test-and-install
  before_script:
    - apt update && apt -y install make cmake libnuma-dev coreutils
  script:
    - cd ./build && make -j$(nproc) tests_smoke &> smoketests.log
    - ../tests/summarise.sh smoketests.log


test_installation:
  tags:
    - docker
  stage: test-and-install
  before_script:
    - apt update && apt -y install make cmake libnuma-dev coreutils
  script:
    - cd ./build && make -j$(nproc) install


build_debug:
  image: gcc:9.3
  tags:
    - docker
  stage: debug-build
  before_script:
    - apt update && apt -y install make cmake libnuma-dev coreutils
  script:
    - rm -rf build install && mkdir -p install && ./configure --prefix=./install --debug-build && cd ./build && make -j$(nproc) && make -j$(nproc) build_tests_all
  artifacts:
    paths:
      - build/
    exclude:
      - build/**/*.o
      - build/**/*.o.d
    expire_in: 30 minutes


test_smoke_debug:
  image: gcc:9.3
  tags:
    - docker
  stage: debug-test
  before_script:
    - apt update && apt -y install make cmake libnuma-dev coreutils
  script:
    - cd ./build && make -j$(nproc) smoketests &> smoketests.log
    - ../tests/summarise.sh smoketests.log


test_install_debug:
  image: gcc:9.3
  tags:
    - docker
  stage: debug-test
  before_script:
    - apt update && apt -y install make cmake libnuma-dev coreutils
  script:
    - cd ./build && make -j$(nproc) install


gitleaks:
  stage: build-and-secrets
  tags:
    - docker
  image:
    name: "zricethezav/gitleaks:v8.0.6"
    entrypoint: [""]
  script: gitleaks detect -v --source .


## Additional tests specific to main branches only

tests_performance:
   image: gcc:9.3
   tags:
     - docker
   stage: test-and-install
   before_script:
     - apt update && apt -y install make cmake libnuma-dev coreutils
   script:
     - cd ./build && make -j$(nproc) performancetests &> performancetests.log
     - ../tests/summarise.sh performancetests.log tests/performance/output/benchmarks tests/performance/output/scaling
   only:
     - master
     - develop


tests_unit_debug:
   image: gcc:9.3
   tags:
     - docker
   stage: debug-test
   before_script:
     - apt update && apt -y install make cmake libnuma-dev coreutils
   script:
     - cd ./build && make -j$(nproc) unittests &> unittests.log
     - ../tests/summarise.sh unittests.log
   only:
     - master
     - develop

