# default settings based on standard Docker image for reproducible build:
# see https://github.com/Algebraic-Programming/ReproducibleBuilds
default:
  tags:
    - docker
  image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/lpf-ubuntu-20.04-gcc

build_and_run:
  script:
    - mkdir -p install build && cd ./build
    - ../bootstrap.sh --prefix=../install --no-nonblocking
    - make -j$(nproc) build_tests_category_smoke
    - mkdir -p ../hyperdags_outputs
    - DATASETS_PATH=${ALP_DATASETS} HYPERDAGS_OUTPUT_FOLDER=$(pwd)/../hyperdags_outputs TEST_BIN_DIR=$(pwd)/tests/smoke ../hyperdags.sh
  artifacts:
    paths:
      - hyperdags_outputs/
    expire_in: 4 weeks
  only:
    - internal-hyperdags-dev