// Auto-generated cost backend configuration
// Generated by: GraphBLAS-cost-modeling/scripts/export_to_alp.py
// Hardware Model: Intel6238Full
//
// This file is automatically generated. Do not edit manually.
// To update: run export_to_alp.py from GraphBLAS-cost-modeling repository

#ifndef GRB_COST_BACKEND_HPP
#define GRB_COST_BACKEND_HPP

// Include cost model implementations
#include "cost_models.hpp"

// Include hardware parameters for this system
#include "hw_params_intel6238full.hpp"

#endif // GRB_COST_BACKEND_HPP
