// Auto-generated cost backend configuration
<<<<<<< HEAD
// Generated by: GraphBLAS-cost-modeling/scripts/export_to_alp.py
<<<<<<< HEAD
// Hardware Model: Intel6238Full
=======
// Generated by: TSIrCo/scripts/export_to_alp.py
// Hardware Model: ARM920
>>>>>>> 84f89c96 (ARM920 changes for new names + model)
=======
// Hardware Model: AMDEPYC9634
>>>>>>> 585c88a9 (Local AMD changes)
//
// This file is automatically generated. Do not edit manually.
// To update: run export_to_alp.py from TSIrCo repository

#ifndef GRB_COST_BACKEND_HPP
#define GRB_COST_BACKEND_HPP

// Include cost model implementations
#include "cost_models.hpp"

// Include hardware parameters for this system
<<<<<<< HEAD
#include "hw_params_intel6238full.hpp"
=======
#include "hw_params_amdepyc9634.hpp"
>>>>>>> 585c88a9 (Local AMD changes)

#endif // GRB_COST_BACKEND_HPP
