#include <iostream>
#include <chrono>
#include <string>
#include <type_traits>
#include <tuple>
#include <utility>
#include <stdexcept>

#include <graphblas/type_traits.hpp>
#include <graphblas/ops.hpp>

// Include cost backend (generated by GraphBLAS-cost-modeling repo)
#include "cost_backend.hpp"

#ifndef _GRB_ENABLE_TRACING
 #define _GRB_ENABLE_TRACING 1
#endif

#ifndef _GRB_COST_MODEL_TEST_MODE
 #define _GRB_COST_MODEL_TEST_MODE 0
#endif

#if _GRB_ENABLE_TRACING

// -- CostPredictor (forward decls)
template< typename Func >
inline const char * getCostPredictorName() { return "unknown"; }

template<>
inline const char * getCostPredictorName< void >() { return "void"; }

template< typename Func >
struct has_tracer : std::false_type {};

// C++11 polyfill for detail::index_sequence / make_index_sequence
#ifndef GRB_COST_DETAIL_INDEX_SEQUENCE
 #define GRB_COST_DETAIL_INDEX_SEQUENCE
namespace detail {

    template< size_t... Is >
    struct index_sequence {
        using type = index_sequence;
        static inline size_t size() { return sizeof...( Is ); }
    };

    template< size_t N, size_t... Is >
    struct make_index_sequence_helper
        : make_index_sequence_helper< N - 1, N - 1, Is... > {};

    template< size_t... Is >
    struct make_index_sequence_helper< 0, Is... > {
        using type = index_sequence< Is... >;
    };

    template< size_t N >
    using make_index_sequence = typename make_index_sequence_helper< N >::type;

} // namespace detail
#endif // GRB_COST_DETAIL_INDEX_SEQUENCE


// Role selector using existing GraphBLAS traits (no decltype/sizeof)
template< class T >
struct RoleName {

    typedef typename std::remove_cv<
        typename std::remove_reference< T >::type
    >::type base_t;

    static const char * get() {
        return pick_semiring(
            std::integral_constant<
                bool, grb::is_semiring< base_t >::value
            >()
        );
    }

private:

    static const char * pick_semiring( std::true_type ) {
        return "Semiring<...>";
    }

    static const char * pick_semiring( std::false_type ) {
        return pick_monoid(
            std::integral_constant<
                bool, grb::is_monoid< base_t >::value
            >()
        );
    }

    static const char * pick_monoid( std::true_type ) {
        return "Monoid<...>";
    }

    static const char * pick_monoid( std::false_type ) {
        return pick_operator(
            std::integral_constant<
                bool, grb::is_operator< base_t >::value
            >()
        );
    }

    static const char * pick_operator( std::true_type ) {
        return "Operator<...>";
    }

    static const char * pick_operator( std::false_type ) {
        return nullptr;
    }
};


// Detect whether grb::operator_name<Base>::present exists (no decltype/sizeof)
struct op_name_present_tag {};
struct op_name_absent_tag {};

template< class U, class = void >
struct op_name_category {
    typedef op_name_absent_tag type;
};

template< class U >
struct op_name_category<
    U,
    typename grb::operator_name<
        typename std::remove_cv<
            typename std::remove_reference< U >::type
        >::type
    >::present
> {
    typedef op_name_present_tag type;
};

template< class U >
using op_name_category_t = typename op_name_category< U >::type;


// TypeName prefers concrete operator_name<> if available, then RoleName
template< class T >
struct TypeName {

    static const char * get() {
        typedef typename std::remove_cv<
            typename std::remove_reference< T >::type
        >::type base_t;
        return pick( op_name_category_t< base_t >() );
    }

private:

    static const char * pick( op_name_present_tag ) {
        typedef typename std::remove_cv<
            typename std::remove_reference< T >::type
        >::type base_t;
        return grb::operator_name< base_t >::name;
    }

    static const char * pick( op_name_absent_tag ) {
        if( const char * role = RoleName< T >::get() ) { return role; }
        return "T";
    }
};


// Fundamental specialisations (extend as needed)
template<>
struct TypeName< double > { static const char * get() { return "double"; } };
template<>
struct TypeName< float > { static const char * get() { return "float"; } };
template<>
struct TypeName< int > { static const char * get() { return "int"; } };
template<>
struct TypeName< unsigned int > { static const char * get() { return "unsigned int"; } };
template<>
struct TypeName< long > { static const char * get() { return "long"; } };
template<>
struct TypeName< size_t > { static const char * get() { return "size_t"; } };
template<>
struct TypeName< char > { static const char * get() { return "char"; } };
template<>
struct TypeName< bool > { static const char * get() { return "bool"; } };

// GraphBLAS containers
template< class D, grb::Backend B, class C >
struct TypeName< grb::Vector< D, B, C > > {
    static const char * get() { return "Vector<...>"; }
};

template< class D, grb::Backend B, class RI, class CI, class NZI >
struct TypeName< grb::Matrix< D, B, RI, CI, NZI > > {
    static const char * get() { return "Matrix<...>"; }
};

template< class T >
inline const char * type_name_cstr() {
    return TypeName< T >::get();
}

template< class T >
inline std::string getTypeName() {
    return std::string( type_name_cstr< T >() );
}


// ===================== unified argument category (Vector / Matrix / Other) ===
struct arg_vector_tag {};
struct arg_matrix_tag {};
struct arg_other_tag  {};

// Primary
template< class T >
struct arg_category {
    typedef arg_other_tag type;
};

// Vector specialization (unqualified only; callers pass remove_cvref<T>::type)
template< class D, grb::Backend B, class C >
struct arg_category< grb::Vector< D, B, C > > {
    typedef arg_vector_tag type;
};

// Matrix specialization (unqualified only)
template< class D, grb::Backend B, class RI, class CI, class NZI >
struct arg_category< grb::Matrix< D, B, RI, CI, NZI > > {
    typedef arg_matrix_tag type;
};

// Normalize cv/ref before dispatch
template< class T >
struct remove_cvref {
    typedef typename std::remove_cv<
        typename std::remove_reference< T >::type
    >::type type;
};


// Vector info via arg_category
template< typename T >
inline std::string getVectorInfoString_impl( const T &arg, arg_vector_tag ) {
    try {
        return std::string( "[size=" )
            + std::to_string( grb::size( arg ) ) + "] ";
    } catch( ... ) {
        return " ";
    }
}

template< typename T >
inline std::string getVectorInfoString_impl( const T &, arg_other_tag ) {
    return " ";
}

template< typename T >
inline std::string getVectorInfoString( const T &arg ) {
    typedef typename remove_cvref< T >::type base_t;
    return getVectorInfoString_impl( arg, typename arg_category< base_t >::type() );
}


// Matrix info via arg_category
template< typename T >
inline std::string getMatrixInfoString_impl( const T &arg, arg_matrix_tag ) {
    try {
        return std::string( "[rows=" )
            + std::to_string( grb::nrows( arg ) )
            + ",cols=" + std::to_string( grb::ncols( arg ) )
            + ",nnz=" + std::to_string( grb::nnz( arg ) )
            + "] ";
    } catch( ... ) {
        return " ";
    }
}

template< typename T >
inline std::string getMatrixInfoString_impl( const T &, arg_other_tag ) {
    return " ";
}

template< typename T >
inline std::string getMatrixInfoString( const T &arg ) {
    typedef typename remove_cvref< T >::type base_t;
    return getMatrixInfoString_impl( arg, typename arg_category< base_t >::type() );
}


// ===================== Argument printing (pure tag-dispatch) ================
template< class T >
inline void printOneArgImpl( const T &arg, arg_vector_tag ) {
    typedef typename std::remove_cv<
        typename std::remove_reference< T >::type
    >::type base_t;
    std::cout << TypeName< base_t >::get();
    std::cout << getVectorInfoString< typename std::remove_reference< T >::type >( arg );
}

template< class T >
inline void printOneArgImpl( const T &arg, arg_matrix_tag ) {
    typedef typename std::remove_cv<
        typename std::remove_reference< T >::type
    >::type base_t;
    std::cout << TypeName< base_t >::get();
    std::cout << getMatrixInfoString< typename std::remove_reference< T >::type >( arg );
}

template< class T >
inline void printOneArgImpl( const T &, arg_other_tag ) {
    typedef typename std::remove_cv<
        typename std::remove_reference< T >::type
    >::type base_t;
    std::cout << TypeName< base_t >::get() << " ";
}

// Single entry that dispatches purely by type (no runtime if/branches)
template< class T >
inline void printOneArg( const T &arg ) {
    typedef typename remove_cvref< T >::type base_t;
    printOneArgImpl( arg, typename arg_category< base_t >::type() );
}

// Base case
inline void printArgTypesHelper() {}

// Recursive case
template< typename T, typename... Args >
void printArgTypesHelper( T &&arg, Args&&... args ) {
    printOneArg( arg );
    printArgTypesHelper( std::forward< Args >( args )... );
}

// Entry point for printing argument types
template< typename... Args >
void printArgTypes( Args&&... args ) {
    std::cout << "[TRACING] Argument types: ";
    printArgTypesHelper( std::forward< Args >( args )... );
    std::cout << std::endl;
}

// Cost prediction framework
// Base template for cost prediction
template<
    typename Func, typename... Args
>
struct CostPredictor {

    // Helper to get argument type names for diagnostic purposes
    template< typename T >
    static std::string getArgTypeName() {
        return getTypeName< T >();
    }

    // Helper to build a comma-separated list of argument type names
    template< size_t... Is >
    static std::string getArgTypeNamesHelper(
        detail::index_sequence< Is... >
    ) {
        std::string result;
        using expander = int[];
        (void) expander{ 0, (void(
            result += (Is == 0 ? "" : ", ") +
                getArgTypeName<
                    typename std::tuple_element<
                        Is, std::tuple< Args... >
                    >::type
                >()
        ), 0 )... };
        return result;
    }

    static std::string getArgTypeNames() {
        return getArgTypeNamesHelper(
            detail::make_index_sequence< sizeof...( Args ) >{}
        );
    }

    static double predict( const Args &... args ) {
        int unused[] = { 0, (void( args ), 0 )... };
        // (void) unused;

        std::string funcName = getCostPredictorName< Func >();
        std::string argTypes = getArgTypeNames();

        std::cout << "[WARNING] *** MISSING COST MODEL ***" << std::endl;
        std::cout << "[WARNING] No specialized cost model for: "
                  << funcName << std::endl;
        std::cout << "[WARNING] With argument types: " << argTypes << std::endl;
        std::cout << "[WARNING] To fix this, add a specialization like:"
                  << std::endl;
        std::cout << "[WARNING] template<...appropriate template params...>"
                  << std::endl;
        std::cout << "[WARNING] struct CostPredictor<" << funcName
                  << "Func, " << argTypes << "> {" << std::endl;
        std::cout << "[WARNING]     static double predict(...) { ... }"
                  << std::endl;
        std::cout << "[WARNING] };" << std::endl;

        if( _GRB_COST_MODEL_TEST_MODE ) {
            std::cerr << "[ERROR] Missing cost model for this function."
                      << std::endl;
            std::cerr << "[ERROR] Function name: " << funcName << std::endl;
        }
        return 1.0;
    }
};

// Special case for the void template parameters - needed for SFINAE detection
template<>
struct CostPredictor< void, void > {
    static double predict() {
        std::cerr << "[ERROR] Missing cost model for this function."
                  << std::endl;
        std::cerr << "[ERROR] Function name: "
                  << getCostPredictorName< void >() << std::endl;
        throw std::runtime_error( "Missing cost model" );
    }
};

// Function object wrappers for each GraphBLAS function (descriptor logic is handled
// by the public traced wrappers; functors just forward without re-entering tracer)
struct EWiseApplyFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::eWiseApply( std::forward< Args >( args )... );
    }
};
struct FoldlFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::foldl( std::forward< Args >( args )... );
    }
};
struct FoldrFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::foldr( std::forward< Args >( args )... );
    }
};
struct DotFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::dot( std::forward< Args >( args )... );
    }
};
struct SetFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::set( std::forward< Args >( args )... );
    }
};
struct ApplyFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::apply( std::forward< Args >( args )... );
    }
};
struct MxvFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::mxv( std::forward< Args >( args )... );
    }
};
struct EWiseAddFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::eWiseAdd( std::forward< Args >( args )... );
    }
};
struct EWiseMulFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::eWiseMul( std::forward< Args >( args )... );
    }
};
struct VxmFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::vxm( std::forward< Args >( args )... );
    }
};
struct EWiseLambdaFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::eWiseLambda( std::forward< Args >( args )... );
    }
};
struct MxmFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::mxm( std::forward< Args >( args )... );
    }
};
struct ZipFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::zip( std::forward< Args >( args )... );
    }
};
struct OuterFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::outer( std::forward< Args >( args )... );
    }
};
struct SelectFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::select( std::forward< Args >( args )... );
    }
};
struct ClearFunc {
    template< typename... Args >
    grb::RC operator()( Args&&... args ) const {
        return ::grb::clear( std::forward< Args >( args )... );
    }
};

// Function tracer class template
template< typename Func >
class FunctionTracer {
private:
    std::string name_;
public:
    explicit FunctionTracer( const std::string & name ) : name_( name ) {
        static_assert( has_tracer< Func >::value,
            "Missing tracer implementation for a GraphBLAS function." );
    }

    template< unsigned int descr = 0, typename... Args >
    grb::RC operator()( Args&&... args ) const {
        std::string function_name = name_;
        if( descr != 0 ) {
            std::string descriptor_name = std::to_string( descr );
            if( descr == grb::descriptors::dense ) descriptor_name = "dense";
            if( descr == grb::descriptors::structural ) descriptor_name = "structural";
            function_name += "<" + descriptor_name + ">";
        }
        std::cout << "\n[TRACING] Entering function: " << function_name
                  << " with " << sizeof...( args ) << " arguments" << std::endl;

        printArgTypes( std::forward< Args >( args )... );

        double predicted_cost = 0.0;
        try {
            predicted_cost = CostPredictor<
                Func, typename std::decay< Args >::type...
            >::predict( args... );

            std::cout << "[TRACING] Predicted cost: " << predicted_cost
                      << " units (cost model: " << getCostPredictorName< Func >()
                      << ")" << std::endl;
        } catch( const std::exception & e ) {
            std::cout << "[ERROR] Cost prediction failed: " << e.what() << std::endl;
            #if _GRB_COST_MODEL_TEST_MODE
                return grb::FAILED;
            #else
                throw;
            #endif
        } catch( ... ) {
            std::cout << "[ERROR] Cost prediction failed with unknown exception" << std::endl;
            #if _GRB_COST_MODEL_TEST_MODE
                return grb::FAILED;
            #else
                throw;
            #endif
        }
#ifndef _CM_DISABLE_EXEC
        auto start = std::chrono::high_resolution_clock::now();
        Func func;
        // Call underlying implementation (already traced once here)
        grb::RC result = func( std::forward< Args >( args )... );
        auto end = std::chrono::high_resolution_clock::now();

        auto duration =
            std::chrono::duration_cast< std::chrono::microseconds >( end - start );
        std::cout << "[TRACING] Exiting function: " << function_name
                  << " (took " << duration.count() << "μs)" << std::endl;

        double cost_time_ratio =
            duration.count() == 0 ? 0.0 :
            predicted_cost / static_cast< double >( duration.count() );
        std::cout << "[TRACING] Cost/time ratio: " << cost_time_ratio
                  << " cost units per microsecond" << std::endl;

        return result;
#else
        return grb::SUCCESS;
#endif
    }
};


// Specializations of CostPredictor for different function/argument combinations
/*=====================================================================*/
/*--------------------------------mxv--------------------------------*/

template< typename T1, typename T2, typename T3, grb::Backend Backend, typename RowIndexType, typename ColIndexType, typename NonzeroIndexType, typename SRingType >
struct CostPredictor< MxvFunc, grb::Vector< T1 >, grb::Matrix< T2, Backend, RowIndexType, ColIndexType, NonzeroIndexType >, grb::Vector< T3 >, SRingType > {
    static double predict( 
        const grb::Vector< T1 > & y, 
        const grb::Matrix< T2, Backend, RowIndexType, ColIndexType, NonzeroIndexType > & A, 
        const grb::Vector< T3 > & x, 
        const SRingType & ring ) {
        // (void)ring;

        try {
            size_t nnz = grb::nnz( A ), n = grb::size( x ), m = grb::size( y ), y_dsize = sizeof( T1 ), x_dsize = sizeof( T3 ), A_dsize = sizeof( T2 ), A_rowptr_size = sizeof( RowIndexType ), A_colidx_size = sizeof( NonzeroIndexType );
			size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] MxvFunc arguments (" << num_threads << " threads): nnz = " << nnz << ", n = " << n << ", m = " << m << ", y_dsize=" << y_dsize << ", x_dsize=" << x_dsize << ", A_dsize= " << A_dsize << ", A_rowptr_size=" << A_rowptr_size << ", A_colidx_size=" << A_colidx_size << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );

            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_csr(
                nnz, n, m, y_dsize, x_dsize, A_dsize, A_rowptr_size, A_colidx_size );
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_csr(
                nnz, n, m, y_dsize, x_dsize, A_dsize, A_rowptr_size, A_colidx_size );
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_csr(
                nnz, n, m, y_dsize, x_dsize, A_dsize, A_rowptr_size, A_colidx_size );
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_csr(
                nnz, n, m, y_dsize, x_dsize, A_dsize, A_rowptr_size, A_colidx_size );
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            
            // Return k-Multi-BSP max cost as before
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<MxvFunc>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<MxvFunc> with Matrix");
        }

    }
};

/*=====================================================================*/
/*--------------------------------set--------------------------------*/

template< typename T1, typename T2 >
struct CostPredictor< SetFunc, grb::Vector< T1 >, grb::Vector< T2 > > {
    static double predict( grb::Vector< T1 > & x, grb::Vector< T2 > & y ){
        // (void)x; 
        // (void)y;
        try {
            size_t n = grb::size( x );
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] SetFunc arguments (" << num_threads << " threads): n = " << n << ", x_dsize=" << sizeof( T1 ) << ", y_dsize=" << sizeof( T2 ) << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );

            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_set( n, 1, sizeof( T1 ), sizeof( T2 ), 0 );
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_set( n, 1, sizeof( T1 ), sizeof( T2 ), 0 );
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_set( n, 1, sizeof( T1 ), sizeof( T2 ), 0 );
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_set( n, 1, sizeof( T1 ), sizeof( T2 ), 0 );
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<SetFunc, Vector, Vector>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<SetFunc> with Vector to Vector");
        }
    }
};

template< typename T1, typename T2 >
struct CostPredictor< SetFunc, grb::Vector< T1 >, T2 > { 
    static double predict( grb::Vector< T1 > & x, const T2 y ){
        try {
            size_t n = grb::size( x );
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] SetFunc arguments (" << num_threads << " threads): n = " << n << ", x_dsize=" << sizeof( T1 ) << ", y_dsize=" << sizeof( T2 ) << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );

            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_set( n, 0, sizeof( T1 ), sizeof( T2 ), 0 );
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_set( n, 0, sizeof( T1 ), sizeof( T2 ), 0 );
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_set( n, 0, sizeof( T1 ), sizeof( T2 ), 0 );
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_set( n, 0, sizeof( T1 ), sizeof( T2 ), 0 );
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<SetFunc, Vector, scalar>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<SetFunc> with Vector to scalar");
        }
    }
};
/*=====================================================================*/
/*--------------------------------clear--------------------------------*/

/*=====================================================================*/
/*--------------------------------apply--------------------------------*/
template< typename T1, typename T2, typename T3, typename Op >
struct CostPredictor< ApplyFunc, T1, T2, T3, Op > {
    static double predict( T1 & x, T2 y, T3 z, const Op &op ){
        // (void)x; 
        // (void)y; 
        // (void)z; 
        // (void)op;
        try {
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] ApplyFunc arguments (" << num_threads << " threads): apply operation" << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
            
            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_apply();
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_apply();
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_apply();
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_apply();
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<ApplyFunc>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<ApplyFunc>");
        }
    }
};

/*=====================================================================*/
/*------------------------------eWiseMul-----------------------------*/
// Specialization for eWiseMul with three vectors
template< typename T1, typename T2, typename T3, typename Op >
struct CostPredictor< EWiseMulFunc, grb::Vector< T1 >, grb::Vector< T2 > , grb::Vector< T3 >, Op > {
    static double predict( 
        const grb::Vector< T1 > & z, 
        const grb::Vector< T2 > & x, 
        const grb::Vector< T3 > & y, 
        const Op & ) {
        try {
            size_t n = grb::size( z );
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] EWiseMulFunc arguments (" << num_threads << " threads): n = " << n << ", z_dsize=" << sizeof( T1 ) << ", x_dsize=" << sizeof( T2 ) << ", y_dsize=" << sizeof( T3 ) << ", x_vec=1, y_vec=1" << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
            
            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 1, 1 );
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 1, 1 );
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 1, 1 );
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 1, 1 );
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<EWiseMulFunc, Vector, Vector, Vector>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<EWiseMulFunc> with three Vectors");
        }
    }
};

// Specialization for eWiseMul with vector-scalar-vector
template< typename T1, typename T2, typename T3, typename Op >
struct CostPredictor< EWiseMulFunc, grb::Vector< T1 >, T2 , grb::Vector< T3 >, Op > {
    static double predict( 
        const grb::Vector< T1 > & z, 
        T2  x, 
        const grb::Vector< T3 > & y, 
        const Op & ) {
        try {
            size_t n = grb::size( z );
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] EWiseMulFunc arguments (" << num_threads << " threads): n = " << n << ", z_dsize=" << sizeof( T1 ) << ", x_dsize=" << sizeof( T2 ) << ", y_dsize=" << sizeof( T3 ) << ", x_vec=0, y_vec=1" << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
            
            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 1 );
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 1 );
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 1 );
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 1 );
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<EWiseMulFunc, Vector, scalar, Vector>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<EWiseMulFunc> with Vector, scalar, Vector");
        }
    }
};

// Specialization for eWiseMul with vector-vector-scalar
template< typename T1, typename T2, typename T3, typename Op >
struct CostPredictor< EWiseMulFunc, grb::Vector< T1 >, grb::Vector< T2 >, T3, Op > {
    static double predict( 
        const grb::Vector< T1 > & z, 
        const grb::Vector< T2 > & x, 
        T3 beta, 
        const Op & ) {
        try {
            size_t n = grb::size( z );
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] EWiseMulFunc arguments (" << num_threads << " threads): n = " << n << ", z_dsize=" << sizeof( T1 ) << ", x_dsize=" << sizeof( T2 ) << ", y_dsize=" << sizeof( T3 ) << ", x_vec=1, y_vec=0" << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
            
            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 1, 0 );
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 1, 0 );
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 1, 0 );
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 1, 0 );
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<EWiseMulFunc, Vector, Vector, scalar>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<EWiseMulFunc> with Vector, Vector, scalar");
        }
    }
};

// Specialization for eWiseMul with vector-scalar-scalar
template< typename T1, typename T2, typename T3, typename Op >
struct CostPredictor< EWiseMulFunc, grb::Vector< T1 >, T2, T3, Op > {
    static double predict( 
        const grb::Vector< T1 > & z, 
        T2 alpha, 
        T3 beta, 
        const Op & ) {
        try {
            size_t n = grb::size( z );
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] EWiseMulFunc arguments (" << num_threads << " threads): n = " << n << ", z_dsize=" << sizeof( T1 ) << ", x_dsize=" << sizeof( T2 ) << ", y_dsize=" << sizeof( T3 ) << ", x_vec=0, y_vec=0" << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
            
            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 0 );
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 0 );
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 0 );
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_eWiseMul( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 0 );
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<EWiseMulFunc, Vector, scalar, scalar>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<EWiseMulFunc> with Vector, scalar, scalar");
        }
    }
};
/*=====================================================================*/
/*------------------------------eWiseApply-----------------------------*/

// Specialization for eWiseApply with two vectors and y scalar
template< typename T1, typename T2, typename T3, typename Op >
struct CostPredictor< EWiseApplyFunc, grb::Vector< T1 >, grb::Vector< T2 >, T3, Op > {
    static double predict( const grb::Vector< T1 > & z, const grb::Vector< T2 > & x, T3 & y, const Op & ) {
        try {
            size_t n = grb::size( z );
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] EWiseApplyFunc arguments (" << num_threads << " threads): n = " << n << ", z_dsize=" << sizeof( T1 ) << ", x_dsize=" << sizeof( T2 ) << ", y_dsize=" << sizeof( T3 ) << ", x_vec=1, y_vec=0" << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
            
            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_eWiseApply( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 1, 0 );
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_eWiseApply( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 1, 0 );
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_eWiseApply( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 1, 0 );
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_eWiseApply( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 1, 0 );
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<EWiseApplyFunc, Vector, Vector, scalar>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<EWiseApplyFunc> with Vector, Vector, scalar");
        }
    }
};

// Specialization for eWiseApply with two vectors and x scalar
template< typename T1, typename T2, typename T3, typename Op >
struct CostPredictor< EWiseApplyFunc, grb::Vector< T1 >, T2, grb::Vector< T3 >, Op > {
    static double predict( const grb::Vector< T1 > & z, T2 & x, const grb::Vector< T3 > & y, const Op & ) {
        try {
            size_t n = grb::size( z );
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] EWiseApplyFunc arguments (" << num_threads << " threads): n = " << n << ", z_dsize=" << sizeof( T1 ) << ", x_dsize=" << sizeof( T2 ) << ", y_dsize=" << sizeof( T3 ) << ", x_vec=0, y_vec=1" << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
            
            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_eWiseApply( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 1 );
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_eWiseApply( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 1 );
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_eWiseApply( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 1 );
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_eWiseApply( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 1 );
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<EWiseApplyFunc, Vector, scalar, Vector>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<EWiseApplyFunc> with Vector, scalar, Vector");
        }
    }
};

// Specialization for eWiseApply with three vectors
template< typename T1, typename T2, typename T3, typename Op >
struct CostPredictor< EWiseApplyFunc, grb::Vector< T1 >, grb::Vector< T2 > , grb::Vector< T3 >, Op > {
    static double predict( 
        const grb::Vector< T1 > & z, 
        const grb::Vector< T2 > & x, 
        const grb::Vector< T3 > & y, 
        const Op & ) {
        // (void)x;
        // (void)y;
        // (void)z;
        try {
            size_t n = grb::size( z );
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] EWiseApplyFunc arguments (" << num_threads << " threads): n = " << n << ", z_dsize=" << sizeof( T1 ) << ", x_dsize=" << sizeof( T2 ) << ", y_dsize=" << sizeof( T3 ) << ", x_vec=0, y_vec=1" << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
            
            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_eWiseApply( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 1 );
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_eWiseApply( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 1 );
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_eWiseApply( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 1 );
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_eWiseApply( n, 
                sizeof( T1 ), sizeof( T2 ), sizeof( T3 ), 0, 1 );
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<EWiseApplyFunc, Vector, Vector, Vector>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<EWiseApplyFunc> with three Vectors");
        }
    }
};

/*=====================================================================*/
/*--------------------------------foldl--------------------------------*/
// ( uint64_t n, size_t x_dsize, size_t y_dsize, bool x_vec, bool y_vec )

template< typename T1, typename T2, typename Monoid >
struct CostPredictor< FoldlFunc, grb::Vector< T1 >, grb::Vector< T2 >, Monoid > {
	static double predict(grb::Vector<T1>& x, const grb::Vector<T2>& y, const Monoid&) {
        // (void)x; 
        // (void)y;
        try {
            size_t n = grb::size( x );
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] FoldlFunc arguments (" << num_threads << " threads): n = " << n << ", x_dsize=" << sizeof( T1 ) << ", y_dsize=" << sizeof( T2 ) << ", x_vec=1, y_vec=1" << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
            
            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_foldl( n, 
                sizeof( T1 ), sizeof( T2 ), 1, 1 );
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_foldl( n, 
                sizeof( T1 ), sizeof( T2 ), 1, 1 );
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_foldl( n, 
                sizeof( T1 ), sizeof( T2 ), 1, 1 );
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_foldl( n, 
                sizeof( T1 ), sizeof( T2 ), 1, 1 );
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<FoldlFunc, Vector, Vector>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<FoldlFunc> with Vector, Vector");
        }
    }
};

template< typename T1, typename T2, typename Monoid >
struct CostPredictor< FoldlFunc, T1 , grb::Vector< T2 >, Monoid > {
	static double predict( T1 & x, const grb::Vector< T2 > & y, const Monoid & ) {
        try {
            size_t n = grb::size( y );
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] FoldlFunc arguments (" << num_threads << " threads): n = " << n << ", x_dsize=" << sizeof( T1 ) << ", y_dsize=" << sizeof( T2 ) << ", x_vec=0, y_vec=1" << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
            
            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_foldl( n, 
                sizeof( T1 ), sizeof( T2 ), 0, 1 );
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_foldl( n, 
                sizeof( T1 ), sizeof( T2 ), 0, 1 );
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_foldl( n, 
                sizeof( T1 ), sizeof( T2 ), 0, 1 );
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_foldl( n, 
                sizeof( T1 ), sizeof( T2 ), 0, 1 );
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<FoldlFunc, scalar, Vector>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<FoldlFunc> with scalar, Vector");
        }
    }
};

template< typename T1, typename T2, typename Monoid >
struct CostPredictor< FoldlFunc, grb::Vector< T1 >, T2 , Monoid > {
	static double predict(grb::Vector< T1 > & x, const T2 & y, const Monoid & ) {
        // (void)x; 
        // (void)y;
        try {
            size_t n = grb::size( x );
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] FoldlFunc arguments (" << num_threads << " threads): n = " << n << ", x_dsize=" << sizeof( T1 ) << ", y_dsize=" << sizeof( T2 ) << ", x_vec=1, y_vec=0" << std::endl;
            return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
            
            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_foldl( n, 
                sizeof( T1 ), sizeof( T2 ), 1, 0 );
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_foldl( n, 
                sizeof( T1 ), sizeof( T2 ), 1, 0 );
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_foldl( n, 
                sizeof( T1 ), sizeof( T2 ), 1, 0 );
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_foldl( n, 
                sizeof( T1 ), sizeof( T2 ), 1, 0 );
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
            
            
            return max_cost_pessimistic;
#endif
        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<FoldlFunc, Vector, scalar>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<FoldlFunc> with Vector, scalar");
        }
    }
};

/*=====================================================================*/
/*--------------------------------foldr--------------------------------*/
template< typename T1, typename T2, typename Monoid >
struct CostPredictor< FoldrFunc, grb::Vector< T1 > , grb::Vector< T2 > , Monoid > {
	static double predict(const grb::Vector< T1 > & x, grb::Vector< T2 > & y, const Monoid & ) {
        // (void)x; 
        // (void)y;
		try {
			size_t n = grb::size( y );
			size_t num_threads = grb::config::OMP::threads();
			
#ifdef _CM_DISABLE_PREDICT
			std::cout << "[TRACING] FoldrFunc arguments (" << num_threads << " threads): n = " << n << ", x_dsize=" << sizeof( T1 ) << ", y_dsize=" << sizeof( T2 ) << ", x_vec=1, y_vec=1" << std::endl;
			return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
			
			// k-Multi-BSP model
			cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_foldr( n, 
				sizeof( T1 ), sizeof( T2 ), 1, 1 );
			cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_foldr( n, 
				sizeof( T1 ), sizeof( T2 ), 1, 1 );
			//double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
			double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
			double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
			
			// Hierarchical Roofline model
			cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_foldr( n, 
				sizeof( T1 ), sizeof( T2 ), 1, 1 );
			double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
			
			// Hierarchical Latency-Aware Roofline model
			cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_foldr( n, 
				sizeof( T1 ), sizeof( T2 ), 1, 1 );
			double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
			
			// Print all model predictions
			//std::cout << "[TRACING] k-Multi-BSP-additive cost: " << sum_cost << " seconds" << std::endl;
			std::cout << "[TRACING] k-Multi-BSP-max cost: " << max_cost_pessimistic << " seconds" << std::endl;
			std::cout << "[TRACING] Hierarchical-Roofline cost: " << hr_cost << " seconds" << std::endl;
			std::cout << "[TRACING] Hierarchical-Latency-Roofline cost: " << hlr_cost << " seconds" << std::endl;
			
			return max_cost_pessimistic;
#endif
		} catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<FoldrFunc, Vector, Vector>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<FoldrFunc> with Vector, Vector");
        }
	}
};

template< typename T1, typename T2, typename Monoid >
struct CostPredictor< FoldrFunc, T1, grb::Vector< T2 >, Monoid > {
	static double predict( const T1 & x, grb::Vector< T2 > & y, const Monoid & ) {
        // (void)x; 
        // (void)y;
		try {
			size_t n = grb::size( y );
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
			std::cout << "[TRACING] FoldrFunc arguments (" << num_threads << " threads): n = " << n << ", x_dsize=" << sizeof( T1 ) << ", y_dsize=" << sizeof( T2 ) << ", x_vec=0, y_vec=1" << std::endl;
			return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
			
			// k-Multi-BSP model
			cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_foldr( n, 
				sizeof( T1 ), sizeof( T2 ), 0, 1 );
			cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_foldr( n, 
				sizeof( T1 ), sizeof( T2 ), 0, 1 );
			//double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
			double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
			double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
			
			// Hierarchical Roofline model
			cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_foldr( n, 
				sizeof( T1 ), sizeof( T2 ), 0, 1 );
			double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
			
			// Hierarchical Latency-Aware Roofline model
			cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_foldr( n, 
				sizeof( T1 ), sizeof( T2 ), 0, 1 );
			double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
			
			// Print all model predictions
			//std::cout << "[TRACING] k-Multi-BSP-additive cost: " << sum_cost << " seconds" << std::endl;
			std::cout << "[TRACING] k-Multi-BSP-max cost: " << max_cost_pessimistic << " seconds" << std::endl;
			std::cout << "[TRACING] Hierarchical-Roofline cost: " << hr_cost << " seconds" << std::endl;
			std::cout << "[TRACING] Hierarchical-Latency-Roofline cost: " << hlr_cost << " seconds" << std::endl;
			
			return max_cost_pessimistic;
#endif
		} catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<FoldrFunc, scalar, Vector>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<FoldrFunc> with scalar, Vector");
        }
	}
};

template< typename T1, typename T2, typename Monoid >
struct CostPredictor< FoldrFunc, grb::Vector< T1 >, T2, Monoid > {
	static double predict(const grb::Vector< T1 > & x, T2 & y, const Monoid & ) {
		try {
			size_t n = grb::size( x );
			size_t num_threads = grb::config::OMP::threads();
			
#ifdef _CM_DISABLE_PREDICT
			std::cout << "[TRACING] FoldrFunc arguments (" << num_threads << " threads): n = " << n << ", x_dsize=" << sizeof( T1 ) << ", y_dsize=" << sizeof( T2 ) << ", x_vec=1, y_vec=0" << std::endl;
			return 0.0;
#else
			cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );
			
			// k-Multi-BSP model
			cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic = cost_models::k_multi_bsp::get_params_foldr( n, 
				sizeof( T1 ), sizeof( T2 ), 1, 0 );
			cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic = cost_models::k_multi_bsp::get_params_foldr( n, 
				sizeof( T1 ), sizeof( T2 ), 1, 0 );
			//double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
			double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
			double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
			
			// Hierarchical Roofline model
			cost_models::hier_roofline::AlgoParameters_p hr_model = cost_models::hier_roofline::get_params_foldr( n, 
				sizeof( T1 ), sizeof( T2 ), 1, 0 );
			double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
			
			// Hierarchical Latency-Aware Roofline model
			cost_models::hier_lat_roofline::AlgoParameters_p hlr_model = cost_models::hier_lat_roofline::get_params_foldr( n, 
				sizeof( T1 ), sizeof( T2 ), 1, 0 );
			double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );
			
			// Print all model predictions
			//std::cout << "[TRACING] k-Multi-BSP-additive cost: " << sum_cost << " seconds" << std::endl;
			std::cout << "[TRACING] k-Multi-BSP-max cost: " << max_cost_pessimistic << " seconds" << std::endl;
			std::cout << "[TRACING] Hierarchical-Roofline cost: " << hr_cost << " seconds" << std::endl;
			std::cout << "[TRACING] Hierarchical-Latency-Roofline cost: " << hlr_cost << " seconds" << std::endl;
			
			return max_cost_pessimistic;
#endif
		} catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<FoldrFunc, Vector, scalar>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<FoldrFunc> with Vector, scalar");
        }
	}
};

// Updated dot specialization
template< typename T0, typename T1, typename T2, typename MonoidType, typename OpType >
struct CostPredictor< DotFunc, T0, grb::Vector< T1 >, grb::Vector< T2 >, MonoidType, OpType > {
    static double predict(T0 z, const grb::Vector< T1 > x, const grb::Vector< T2 > y, MonoidType monoid, OpType op) {
        // (void)z; 
        // (void)monoid; 
        // (void)op;
        try {
            std::cout << "[TRACING] Using catch-all 5-argument dot predictor" << std::endl;

            size_t n = grb::size( x );

            // Get hardware parameters
            size_t num_threads = grb::config::OMP::threads();
            
#ifdef _CM_DISABLE_PREDICT
            std::cout << "[TRACING] DotFunc arguments (" << num_threads << " threads): n = " << n << ", z_dsize=" << sizeof( T0 ) << ", x_dsize=" << sizeof( T1 ) << ", y_dsize=" << sizeof( T2 ) << std::endl;
            return 0.0;
#else
            cost_models::HW_model::HWParameters hw_model = cost_models::HW_model::select_hw_model_auto( num_threads, dis_system_params );

            // k-Multi-BSP model
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_optimistic =
                cost_models::k_multi_bsp::get_params_dot(n, sizeof(T0), sizeof(T1), sizeof(T2));
            cost_models::k_multi_bsp::AlgoParameters_p k_bsp_model_pessimistic =
                cost_models::k_multi_bsp::get_params_dot(n, sizeof(T0), sizeof(T1), sizeof(T2));
            //double sum_cost = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model, num_threads, "sum" );
            double max_cost_optimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_optimistic, num_threads, "max", true );
            double max_cost_pessimistic = cost_models::k_multi_bsp::predict_cost( &hw_model, k_bsp_model_pessimistic, num_threads, "max", false );
            
            // Hierarchical Roofline model
            cost_models::hier_roofline::AlgoParameters_p hr_model =
                cost_models::hier_roofline::get_params_dot(n, sizeof(T0), sizeof(T1), sizeof(T2));
            double hr_cost = cost_models::hier_roofline::predict_cost( &hw_model, hr_model, num_threads );
            
            // Hierarchical Latency-Aware Roofline model
            cost_models::hier_lat_roofline::AlgoParameters_p hlr_model =
                cost_models::hier_lat_roofline::get_params_dot(n, sizeof(T0), sizeof(T1), sizeof(T2));
            double hlr_cost = cost_models::hier_lat_roofline::predict_cost( &hw_model, hlr_model, num_threads );

            return max_cost_pessimistic;
#endif

        } catch(const std::exception& e) {
            throw std::runtime_error("Error in CostPredictor<DotFunc>: " + std::string(e.what()));
        } catch(...) {
            throw std::runtime_error("Unknown error in CostPredictor<DotFunc> with 5 arguments");
        }
    }
};

/*=====================================================================*/
/*---------------------------------add---------------------------------*/

/*=====================================================================*/
/*---------------------------------mul---------------------------------*/

/*=====================================================================*/
/*--------------------------------muladd-------------------------------*/



// Names for each wrapped GraphBLAS function
template<> inline const char* getCostPredictorName<EWiseApplyFunc>() { return "eWiseApply"; }
template<> inline const char* getCostPredictorName<FoldlFunc>()      { return "foldl"; }
template<> inline const char* getCostPredictorName<FoldrFunc>()      { return "foldr"; }
template<> inline const char* getCostPredictorName<DotFunc>()        { return "dot"; }
template<> inline const char* getCostPredictorName<SetFunc>()        { return "set"; }
template<> inline const char* getCostPredictorName<ApplyFunc>()      { return "apply"; }
template<> inline const char* getCostPredictorName<MxvFunc>()        { return "mxv"; }
template<> inline const char* getCostPredictorName<EWiseAddFunc>()   { return "eWiseAdd"; }
template<> inline const char* getCostPredictorName<EWiseMulFunc>() { return "eWiseMul"; }
template<> inline const char* getCostPredictorName<VxmFunc>()        { return "vxm"; }
template<> inline const char* getCostPredictorName<EWiseLambdaFunc>(){ return "eWiseLambda"; }
template<> inline const char* getCostPredictorName<MxmFunc>()        { return "mxm"; }
template<> inline const char* getCostPredictorName<ZipFunc>()        { return "zip"; }
template<> inline const char* getCostPredictorName<OuterFunc>()      { return "outer"; }
template<> inline const char* getCostPredictorName<SelectFunc>()     { return "select"; }
template<> inline const char* getCostPredictorName<ClearFunc>()      { return "clear"; }

// Mark which wrappers have tracers (for the static_assert in FunctionTracer)
template<> struct has_tracer<EWiseApplyFunc>   : std::true_type {};
template<> struct has_tracer<FoldlFunc>        : std::true_type {};
template<> struct has_tracer<FoldrFunc>        : std::true_type {};
template<> struct has_tracer<DotFunc>          : std::true_type {};
template<> struct has_tracer<SetFunc>          : std::true_type {};
template<> struct has_tracer<ApplyFunc>        : std::true_type {};
template<> struct has_tracer<MxvFunc>          : std::true_type {};
template<> struct has_tracer<EWiseAddFunc>     : std::true_type {};
template<> struct has_tracer<EWiseMulFunc>     : std::true_type {};
template<> struct has_tracer<VxmFunc>          : std::true_type {};
template<> struct has_tracer<EWiseLambdaFunc>  : std::true_type {};
template<> struct has_tracer<MxmFunc>          : std::true_type {};
template<> struct has_tracer<ZipFunc>          : std::true_type {};
template<> struct has_tracer<OuterFunc>        : std::true_type {};
template<> struct has_tracer<SelectFunc>       : std::true_type {};
template<> struct has_tracer<ClearFunc>        : std::true_type {};



// redefine the functions in the grb namespace with tracing
namespace grb {
    // Create tracers for each function
    static const FunctionTracer< EWiseApplyFunc > eWiseApplyTracer( "eWiseApply" );
    static const FunctionTracer< FoldlFunc > foldlTracer( "foldl" );
    static const FunctionTracer< FoldrFunc > foldrTracer( "foldr" );
    static const FunctionTracer< DotFunc > dotTracer( "dot" );
    static const FunctionTracer< SetFunc > setTracer( "set" );
    static const FunctionTracer< ApplyFunc > applyTracer( "apply" );
    static const FunctionTracer< MxvFunc > mxvTracer( "mxv" );
    static const FunctionTracer< EWiseAddFunc > eWiseAddTracer( "eWiseAdd" );
    static const FunctionTracer< EWiseMulFunc > eWiseMulTracer( "eWiseMul" );
    static const FunctionTracer< VxmFunc > vxmTracer( "vxm" );
    static const FunctionTracer< EWiseLambdaFunc > eWiseLambdaTracer( "eWiseLambda" );
    static const FunctionTracer< MxmFunc > mxmTracer( "mxm" );
    static const FunctionTracer< ZipFunc > zipTracer( "zip" );
    static const FunctionTracer< OuterFunc > outerTracer( "outer" );
    static const FunctionTracer< SelectFunc > selectTracer( "select" );
    static const FunctionTracer< ClearFunc > clearTracer( "clear" );


    template< unsigned int descr = 0, typename... Args >
    inline grb::RC eWiseApply( Args&&... args ) {
        return eWiseApplyTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    template< unsigned int descr = 0, typename... Args >
    inline grb::RC foldl( Args&&... args ) {
        return foldlTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    template< unsigned int descr = 0, typename... Args >
    inline grb::RC foldr( Args&&... args ) {
        return foldrTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    template< unsigned int descr = 0, typename... Args >
    inline grb::RC dot( Args&&... args ) {
        return dotTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    template< unsigned int descr = descriptors::no_operation, typename... Args >
    inline grb::RC set( Args&&... args ) {
        return setTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    // Note: we avoid defining reference-specific `set` overloads here because
    // the reference backend already provides identical templates in
    // `reference/io.hpp`. 

    template< unsigned int descr = descriptors::no_operation, typename Coords, typename T >
    inline grb::RC set(
        grb::Vector< T, grb::reference_omp, Coords > & x,
        const T val,
        const grb::Phase & phase = grb::EXECUTE
    ) {
        return setTracer.template operator()< descr >( x, val, phase );
    }

    template< unsigned int descr = descriptors::no_operation, typename Coords, typename T >
    inline grb::RC set(
        grb::Vector< T, grb::reference, Coords > & x,
        const T val,
        const grb::Phase & phase = grb::EXECUTE
    ) {
        return setTracer.template operator()< descr >( x, val, phase );
    }

    template< unsigned int descr = descriptors::no_operation, typename OutputType, grb::Backend B, typename Coords, typename InputType >
    inline grb::RC set(
        grb::Vector< OutputType, B, Coords > & x,
        const grb::Vector< InputType, B, Coords > & y,
        const grb::Phase & phase = grb::EXECUTE
    ) {
        return setTracer.template operator()< descr >( x, y, phase );
    }

    template< unsigned int descr = 0, typename... Args >
    inline grb::RC apply( Args&&... args ) {
        return applyTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    template< unsigned int descr = 0, typename... Args >
    inline grb::RC mxv( Args&&... args ) {
        return mxvTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    template< unsigned int descr = 0, typename... Args >
    inline grb::RC eWiseAdd( Args&&... args ) {
        return eWiseAddTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    template< unsigned int descr = 0, typename... Args >
    inline grb::RC eWiseMul( Args&&... args ) {
        return eWiseMulTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    template< unsigned int descr = 0, typename... Args >
    inline grb::RC vxm( Args&&... args ) {
        return vxmTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    // Note: eWiseLambda is handled via a proxy below to avoid interfering with existing user code
    // template< unsigned int descr = 0, typename... Args >
    // inline grb::RC eWiseLambda( Args&&... args ) {
    //     return eWiseLambdaTracer.template operator()< descr >( std::forward< Args >( args )... );
    // }

    template< unsigned int descr = 0, typename... Args >
    inline grb::RC mxm( Args&&... args ) {
        return mxmTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    template< unsigned int descr = 0, typename... Args >
    inline grb::RC zip( Args&&... args ) {
        return zipTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    template< unsigned int descr = 0, typename... Args >
    inline grb::RC outer( Args&&... args ) {
        return outerTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    template< unsigned int descr = 0, typename... Args >
    inline grb::RC select( Args&&... args ) {
        return selectTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

    template< unsigned int descr = 0, typename... Args >
    inline grb::RC clear( Args&&... args ) {
        return clearTracer.template operator()< descr >( std::forward< Args >( args )... );
    }

} // namespace grb



#ifndef GRB_EWISELAMBDA_TRACING_PROXY_DEFINED
#define GRB_EWISELAMBDA_TRACING_PROXY_DEFINED

namespace grb {
    namespace tracing_detail {

        struct eWiseLambda_proxy_t {
            template< 
                unsigned int descr = 0, 
                class F, 
                class... Args 
            >
            inline grb::RC operator()( F && f, Args &&... args ) const {
                // Re-use existing tracer object:
                return eWiseLambdaTracer.template operator()< descr >(
                    std::forward< F >( f ),
                    std::forward< Args >( args )...
                );
            }
        };

        static const eWiseLambda_proxy_t eWiseLambda_proxy;

    } // namespace tracing_detail
} // namespace grb

// Redirect only subsequent user code tokens; does not affect already parsed defs.
#ifndef eWiseLambda
#define eWiseLambda grb::tracing_detail::eWiseLambda_proxy
#endif

#endif // GRB_EWISELAMBDA_TRACING_PROXY_DEFINED



#endif // _GRB_ENABLE_TRACING