from setuptools import setup, Extension
from setuptools import find_packages
from setuptools.command.build_ext import build_ext as _build_ext
import sys
import os
import glob
import shutil
import sysconfig
import pathlib
bdist_wheel_cmd = None
try:
    # Used to mark wheel as non-pure when bundling a prebuilt .so
    from wheel.bdist_wheel import bdist_wheel as _bdist_wheel

    class bdist_wheel(_bdist_wheel):
        def finalize_options(self):
            super().finalize_options()
            # wheel contains a native shared object; mark as platform-specific
            self.root_is_pure = False

    bdist_wheel_cmd = bdist_wheel
except Exception:
    bdist_wheel_cmd = None
_have_pybind11 = False
try:
    # import lazily — only needed when we build from sources
    from pybind11.setup_helpers import Pybind11Extension, build_ext
    _have_pybind11 = True
except Exception:
    Pybind11Extension = None
    build_ext = None

here = os.path.abspath(os.path.dirname(__file__))

prebuilt_env = os.environ.get("PREBUILT_PYALP_SO") or os.environ.get("PYALP_PREBUILT_SO")

# Discover prebuilt backend shared objects in the CMake build tree.
def find_all_prebuilt():
    supported = ["pyalp_ref", "pyalp_omp", "pyalp_nonblocking", "_pyalp"]
    py_tag = f"cp{sys.version_info[0]}{sys.version_info[1]}"
    mapping = {}
    for mod in supported:
        patterns = [
            os.path.join(here, '..', 'build', '**', f'{mod}*.so'),
            os.path.join(here, '..', 'build', '**', f'{mod}*.pyd'),
        ]
        found = []
        for pat in patterns:
            found.extend(glob.glob(pat, recursive=True))
        if not found:
            continue
        # Prefer candidate matching current ABI tag in filename or parent dir
        matching = [c for c in found if py_tag in os.path.basename(c) or py_tag in os.path.basename(os.path.dirname(c))]
        chosen = (matching or found)[0]
        mapping[mod] = os.path.abspath(chosen)
    return mapping

# Determine prebuilt modules mapping. If user specified a single PREBUILT env var,
# map it to its basename (module name) where possible; otherwise search the build tree.
prebuilt_modules = {}
if prebuilt_env:
    # map provided path to module name by deriving filename stem
    bn = os.path.basename(prebuilt_env)
    modname = bn.split('.', 1)[0]
    prebuilt_modules[modname] = os.path.abspath(prebuilt_env)
else:
    prebuilt_modules = find_all_prebuilt()

package_data = {}
ext_modules = []

class build_ext_copy_prebuilt(_build_ext):
    """Custom build_ext that copies a prebuilt shared object into the build dir.

    This ensures the extension is installed into platlib and the wheel is valid
    for auditwheel repair.
    """

    def build_extension(self, ext):
        # Determine target path for the extension
        target_path = self.get_ext_fullpath(ext.name)
        os.makedirs(os.path.dirname(target_path), exist_ok=True)
        # Choose the source prebuilt file corresponding to this extension
        # ext.name is like 'pyalp.<module_name>'
        mod_fullname = ext.name
        modname = mod_fullname.split('.', 1)[1] if '.' in mod_fullname else mod_fullname

        # Priority: explicit env var -> mapping discovered earlier -> glob search
        src = os.environ.get("PREBUILT_PYALP_SO") or os.environ.get("PYALP_PREBUILT_SO")
        if not src:
            src = prebuilt_modules.get(modname)
        if not src:
            # Try a targeted glob for this module as a last resort
            candidates = glob.glob(os.path.join(here, '..', 'build', '**', f'{modname}*.so'), recursive=True)
            candidates += glob.glob(os.path.join(here, '..', 'build', '**', f'{modname}*.pyd'), recursive=True)
            py_tag = f"cp{sys.version_info[0]}{sys.version_info[1]}"
            matching = [c for c in candidates if py_tag in os.path.basename(c) or py_tag in os.path.basename(os.path.dirname(c))]
            src = (matching or candidates)[:1]
            src = os.path.abspath(src[0]) if src else None

        if not src or not os.path.exists(src):
            raise RuntimeError(f"Prebuilt pyalp shared object not found for module '{modname}' during build_ext")
        shutil.copyfile(src, target_path)

        # The _metadata.py file is generated by CMake in the build directory.
        # We need to find it and copy it to the same directory as the extension.
        ext_build_dir = os.path.dirname(target_path)
        # CMAKE_BUILD_DIR is set by the cibuildwheel before_build script to the per-ABI build directory
        cmake_build_dir = os.environ.get("CMAKE_BUILD_DIR")
        if cmake_build_dir:
            metadata_src_path = os.path.join(cmake_build_dir, "pyalp_metadata.py")
            metadata_dest_path = os.path.join(ext_build_dir, "_metadata.py")
            if os.path.exists(metadata_src_path):
                print(f"Copying generated metadata from {metadata_src_path} to {metadata_dest_path}")
                shutil.copyfile(metadata_src_path, metadata_dest_path)
            else:
                print(f"Warning: Generated metadata file not found at {metadata_src_path}. Skipping copy.")
        else:
            # Fall back: try to locate the generated metadata under any per-ABI
            # build directory (e.g. ../build/cp310, ../build/cp39, ...).
            # This avoids relying strictly on the CMAKE_BUILD_DIR env var which
            # may not always be propagated into the isolated build environment.
            search_pattern = os.path.join(here, '..', 'build', '**', 'pyalp_metadata.py')
            candidates = glob.glob(search_pattern, recursive=True)
            # Prefer candidate matching the current Python ABI tag if present
            py_tag = f"cp{sys.version_info[0]}{sys.version_info[1]}"
            matching = [c for c in candidates if py_tag in os.path.basename(os.path.dirname(c)) or py_tag in os.path.basename(c)]
            chosen = (matching or candidates)[:1]
            if chosen:
                metadata_src_path = os.path.abspath(chosen[0])
                metadata_dest_path = os.path.join(ext_build_dir, "_metadata.py")
                print(f"Copying generated metadata from {metadata_src_path} to {metadata_dest_path} (discovered by glob search)")
                shutil.copyfile(metadata_src_path, metadata_dest_path)
            else:
                print("Warning: CMAKE_BUILD_DIR not set and no generated metadata found under ../build. Skipping metadata file copy.")

if prebuilt_modules:
    # Create an Extension for each discovered prebuilt module so setuptools will
    # place the shared object into the package (platlib).
    for modname in prebuilt_modules.keys():
        ext_modules.append(Extension(f"pyalp.{modname}", sources=[]))
else:
    if not _have_pybind11:
        raise RuntimeError("pybind11 is required to build the extension from sources. Install pybind11 or provide PREBUILT_PYALP_SO to bundle a prebuilt .so.")
    assert Pybind11Extension is not None
    ext_modules = [
        Pybind11Extension(
            "pyalp._pyalp",
            ["src/pyalp/bindings.cpp"],
            include_dirs=[
                os.path.join(here, "src"),
                os.path.join(here, "src", "pyalp"),
                os.path.join(here, "extern", "pybind11", "include"),
                os.path.normpath(os.path.join(here, "..", "include")),
            ],
            define_macros=[("PYALP_MODULE_NAME", "_pyalp")],
            cxx_std=14,
        )
    ]

setup_kwargs = {
    "name": "pyalp",
    "version": "0.8.1",
    "description": "pyalp package (C++ bindings)",
    "packages": find_packages(where="src"),
    "package_dir": {"": "src"},
    # Ensure generated metadata is included in the wheel. The build process
    # will copy the generated file to the package build dir as `_metadata.py`.
    "package_data": {"pyalp": ["_metadata.py"]},
    "ext_modules": ext_modules,
    "include_package_data": True,
}

# Supply cmdclass entries for build_ext (copy-prebuilt or pybind11) and bdist_wheel
cmdclass = {}
# If we detected prebuilt modules, use the copy-prebuilt build_ext which copies
# each discovered shared object into the package build directory.
if prebuilt_modules:
    cmdclass["build_ext"] = build_ext_copy_prebuilt
elif build_ext is not None:
    cmdclass["build_ext"] = build_ext
if bdist_wheel_cmd is not None:
    cmdclass["bdist_wheel"] = bdist_wheel_cmd
if cmdclass:
    setup_kwargs["cmdclass"] = cmdclass

setup(**setup_kwargs)
