
name: smoke-tests

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install required packages
      run: sudo apt-get install -y libnuma-dev

    - name: Configure
      run: mkdir build && cd build && ../bootstrap.sh --prefix=../install

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j2

    - name: Install
      working-directory: ${{github.workspace}}/build
      run: make -j2 install

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: make -j2 smoketests

