
name: smoke-tests

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        category: ['smoke']
        build-type: ['','--debug-build']

    steps:
    - uses: actions/checkout@v3

    - name: Install required packages
      run: sudo apt-get install -y libnuma-dev

    - name: Configure
      run: mkdir build && cd build && ../bootstrap.sh --prefix=../install ${{ matrix.build-type }}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j$(nproc) && make -j$(nproc) build_tests_category_${{ matrix.category }}

    - name: Install
      working-directory: ${{github.workspace}}/build
      run: make -j$(nproc) install

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -L "mode:${{ matrix.category }}" --output-junit ${{ matrix.category }}.xml --output-on-failure || true

    - name: Check
      working-directory: ${{github.workspace}}/build
      run: python3 ../tools/ctest-junit-parse.py --categories ${{ matrix.category }} --xmls-dir $(pwd) --remove-successful-logs-from $(pwd)/tests
